name: Update Dependency Graph

on:
  push:
    branches:
      - master # default branch of the project

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v3.2.3
